services:
  - type: web
    name: divinegpt-rag_service
    env: docker
    repo: https://github.com/Coder-Harshit/divinegpt
    dockerfile: ./rag_service/Dockerfile
    buildCommand: docker built -t divinegpt-rag_service .
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8001
    plan: free
    envVars:
      - key: RAG_SERVICE_PORT
        value: "8001"

  - type: web
    name: divinegpt-llm_service
    env: docker
    repo: https://github.com/Coder-Harshit/divinegpt
    dockerfile: ./llm_service/Dockerfile
    buildCommand: docker built -t divinegpt-llm_service .
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: LLM_SERVICE_PORT
        value: "8000"

  - type: web
    name: divinegpt-t2s_service
    env: docker
    repo: https://github.com/Coder-Harshit/divinegpt
    dockerfile: ./t2s_service/Dockerfile
    buildCommand: docker built -t divinegpt-t2s_service .
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8003
    plan: free
    envVars:
      - key: T2S_SERVICE_PORT
        value: "8003"
