// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbigyqpwubbepzbcmaxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiaWd5cXB3dWJiZXB6YmNtYXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzgwOTIsImV4cCI6MjA2MTAxNDA5Mn0.ql83q_JPe2Cs1mKAF3ANkeAYsqi4FTkC32WZMe28MpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);